[app]
overall = { bg = "#ffffff" }

[mgr]
cwd = { fg = "#0031a9" }
border_style = { fg = "#9f9f9f" }
marker_selected = { fg = "#000000", bg = "#c4c4c4", bold = true }
marker_marked = { fg = "#721045", bold = true }
count_selected = { fg = "#000000", bg = "#c4c4c4" }
find_keyword = { fg = "#695500", bold = true }
find_position = { fg = "#224960" }

[indicator]
parent = { fg = "#595959" }
current = { fg = "#000000", bg = "#c4c4c4" }
preview = { fg = "#595959", bg = "#f2f2f2" }
padding = { open = " ", close = " " }

[tabs]
active = { fg = "#000000", bg = "#c4c4c4", bold = true }
inactive = { fg = "#595959" }

[mode]
normal_main = { fg = "#000000", bg = "#c4c4c4" }
normal_alt  = { fg = "#595959" }
select_main = { fg = "#000000", bg = "#c4c4c4" }
select_alt  = { fg = "#595959" }
unset_main  = { fg = "#000000" }
unset_alt   = { fg = "#595959" }

[status]
overall = { fg = "#000000", bg = "#f2f2f2" }
perm_type = { fg = "#0031a9" }
perm_read = { fg = "#006800" }
perm_write = { fg = "#695500" }
perm_exec = { fg = "#702000" }
progress_normal = { fg = "#006800" }
progress_error = { fg = "#702000" }
