[app]
overall = { bg = "#0d0e1c" }

[mgr]
cwd = { fg = "#2fafff" }
border_style = { fg = "#61647a" }
marker_selected = { fg = "#ffffff", bg = "#4a4f69", bold = true }
marker_marked = { fg = "#feacd0", bold = true }
count_selected = { fg = "#ffffff", bg = "#4a4f69" }
find_keyword = { fg = "#d0bc00", bold = true }
find_position = { fg = "#c6daff" }

[indicator]
parent = { fg = "#989898" }
current = { fg = "#ffffff", bg = "#4a4f69" }
preview = { fg = "#989898", bg = "#1d2235" }
padding = { open = " ", close = " " }

[tabs]
active = { fg = "#ffffff", bg = "#4a4f69", bold = true }
inactive = { fg = "#989898" }

[mode]
normal_main = { fg = "#ffffff", bg = "#4a4f69" }
normal_alt  = { fg = "#989898" }
select_main = { fg = "#ffffff", bg = "#4a4f69" }
select_alt  = { fg = "#989898" }
unset_main  = { fg = "#ffffff" }
unset_alt   = { fg = "#989898" }

[status]
overall = { fg = "#ffffff", bg = "#1d2235" }
perm_type = { fg = "#2fafff" }
perm_read = { fg = "#44bc44" }
perm_write = { fg = "#d0bc00" }
perm_exec = { fg = "#ff5f59" }
progress_normal = { fg = "#44bc44" }
progress_error = { fg = "#ff5f59" }
